{% set name = "yaqd-vici" %}
{% set version = "2022.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/yaqd-vici-{{ version }}.tar.gz
  sha256: 61e39d71169f33ca8b9bf7fdb827099bfdcb49d846af114d031d32e30aecdebb

build:
  number: 1
  noarch: python
  entry_points:
    - yaqd-vici-two-position = yaqd_vici._vici_two_position:ViciTwoPosition.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit
    - pip
    - python {{ python_min }}
  run:
    - pyserial
    - python >={{ python_min }}
    - yaqd-core >=2021.2.1

test:
  imports:
    - yaqd_vici
  commands:
    - pip check
    - yaqd-vici-two-position --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://yaq.fyi
  summary: yaq support for VICI hardware
  dev_url: https://gitlab.com/yaq/yaqd-vici
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
